pipeline {
    agent any

    stages {
        stage("Initial Cleanup") {
            steps {
                dir("${WORKSPACE}") {
                    deleteDir()
                }
            }
        }

        stage('Build') {
            steps {
                script {
                    sh 'echo "Building Stage"'
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    sh 'echo "Testing Stage"'
                }
            }
        }

        stage('Package') {
            steps {
                script {
                    sh 'echo "Package App"'
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    sh 'echo "Deploying to dev"'
                }
            }
        }

        stage("Clean up") {
            steps {
                cleanWs()
            }
        }
    }
}
